import mongoose from 'mongoose';

const PostSchema = mongoose.Schema(
    {//this is an Object storing all these fields
        userId:{
            type:String,
            required:true,
        },
        firstName:{
            type:String,
            required:true
        },
        lastName:{
            type:String,
            required:true
        },

        location: String,
        description: String,
        userPicturePath: String,


        likes: { //if you like it you will be in this map it always be true and if you have not liked it you will be removed from the map
            type:Map, //using map over array is much more effecient, we don't ahve to search get TC=O(1)
            of: Boolean,
        }, 
        
        comments:{
            type:Array,
            default: []
        }
    },

    { timestaps:true }
)

const Post = mongoose.model("Post", PostSchema) // "Post" is the name of the Model, for db the collection name is autogenerated by mongoose  

export default Post